M48
; DRILL file {KiCad 7.0.7} date 2024 March 28, Thursday 15:45:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-28T15:45:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.550
%
G90
G05
T1
X127.465Y-70.38
X132.315Y-70.38
T2
X127.165Y-67.35
X132.615Y-67.35
T3
X122.01Y-55.62
T4
X122.01Y-119.02
X137.75Y-63.82
T0
M30
