M48
; DRILL file {KiCad 7.0.2} date Wed May  3 22:51:00 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-03T22:51:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.100
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.400
%
G90
G05
T1
X15.068Y38.024
T2
X12.908Y27.558
T0
M30
